### ISSUE TITLE
Failing the automatic install on jessie amazon base image 

### ISSUE THREAD

**Issue by arthurlogilab** [mika/jenkins-debian-glue#170]
On a  fresh debian-jessie-amd64-hvm-2016-02-17-ebs (ami-11c57862)

Running https://jenkins-debian-glue.org/getting_started/automatic/ fails on 

```
# wget --no-check-certificate https://raw.github.com/mika/jenkins-debian-glue/master/puppet/apply.sh
# sudo bash ./apply.sh your_password
[snip]
Setting up puppet (3.7.2-4) ...
Job for puppet.service failed. See 'systemctl status puppet.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript puppet, action "start" failed.
Setting up ruby-rgen (0.7.0-1) ...
Setting up ruby-selinux (2.3-2) ...
Setting up virt-what (1.14-1) ...
Processing triggers for libc-bin (2.19-18+deb8u3) ...
Processing triggers for systemd (215-17+deb8u3) ...
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so: symbol SSLv2_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference - /usr/lib/x86_64-linux-gnu/ruby/2.1.0/openssl.so (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/openssl.rb:17:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/util/monkey_patches.rb:171:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/util.rb:16:in `<module:Util>'
        from /usr/lib/ruby/vendor_ruby/puppet/util.rb:15:in `<module:Puppet>'
        from /usr/lib/ruby/vendor_ruby/puppet/util.rb:14:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet.rb:8:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:12:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/bin/puppet:7:in `<main>'
Fatal error during puppet run. :(
```

**Comment by arthurlogilab** [comment]
I did an apt-get upgrade an then relaunched the script and it seemed to finish the job.

**Comment by mika** [comment]
Yes, you're running an outdated AMI, see https://wiki.debian.org/Cloud/AmazonEC2Image/Jessie for up2date ones.
